### ISSUE TITLE
how to load external resources?

### ISSUE THREAD

**Issue by cachrisman** [shiftlab/contentful-react-ui-extension#2]
I'm trying to use this boilerplate to make a UI extension but am running into the Contentful UI extension size limit of 200kb. I know it's possible to load react and other dependencies remotely, but I'm not too familiar with create-react-app and how it works. Normally I'd just include a `script` tag in the index.html file like so:
```
<script src="https://unpkg.com/react@16/dist/react.js"></script>
```

but index.html is completely generated by the build process, no?

Any help would be greatly appreciated! Thanks!

**Comment by cachrisman** [comment]
never mind! I figured it out. I just had to add the script tag to the `/public/index.html` file and then wrap the relevant line in `App.js` with

```
/*eslint-disable no-undef*/
const Tags = ReactTags.WithContext
/*eslint-enable no-undef*/
```

Hope this might help others!

**Comment by JasonStoltz** [comment]
Thanks @cachrisman for the follow up. I didn't realize there was size limit on UI extensions. I'll see if I can update this to keep pull in some of the larger dependencies from a CDN, like you mention.
